# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

viterbi_bio_cpp <- function(obs, pi, A, B) {
    .Call('_viterbiM2_viterbi_bio_cpp', PACKAGE = 'viterbiM2', obs, pi, A, B)
}

